markdown: kramdown
permalink: none
exclude:
  - CNAME
  - Gemfile
  - LICENSE
  - Rakefile
  - README.md

layouts: ./_layouts

config:
  name: ManiMejia.me
  description: 'Artist, Athlete, and Engineer'
  author:
    name: Manuel Mejia
    url: http://manimejia.me
  lang: en
  favicons:
    - /resources/favicon-152.png
  topbar:
    toggle: Menu
    right:
      - name: About
        url: /about/
      - name: Guide
        url: /guide/
      - name: Blog
        url: /blog/
      - name: Repository
        url: https://github.com/penibelst/jekyll-noita
        class: small button
