markdown: kramdown
permalink: none
include: 
  - blog 
exclude:
  - CNAME
  - Gemfile
  - LICENSE
  - Rakefile
  - README.md
  - resources
  - foundation/scss

sass:
   sass_dir: theme/foundation/scss

layouts: ./_layouts

available_libraries:
  - 
    name: foundation 
    js: 
      - /theme/foundation/js/vendor/jquery.js
      - /theme/foundation/js/vendor/modernizr.js
      - /theme/foundation/js/foundation.js
    css: 
      - /theme/foundation/icons/foundation-icons.css
      - /theme/foundation/css/normalize.css
  - 
    name: skrollr
    js: 
      - /theme/skrollr/skrollr.min.js
  - 
    name: skrollr_stylesheets
    js: 
      - /theme/skrollr/skrollr.stylesheets.min.js
  - 
    name: skrollr_menu
    js: 
      - /theme/skrollr/skrollr.menu.min.js
  - 
    name: slick
    js: 
      - /theme/slick/slick.min.js
    css: 
      - /theme/slick/slick.css
  - 
    name: manimejia
    js: 
      - /theme/manimejia/manimejia.js
    #- /theme/manimejia/foundation.accordion.mm.js
    css:
      - "http://fonts.googleapis.com/css?family=Josefin+Sans:300,400|Open+Sans:400italic,600,400" 
      - /theme/manimejia/foundation-manimejia.css


defaults:
  - 
    scope: # All Posts
      type: "post"
      path: ""
    values:
      libraries: 
        - foundation
        - manimejia
  -
    scope: # All Pages
      type: "page"
      path: ""
    values:
      title: 
      category: 
      tags: 
      layout: "page"
      printable: false
      assetpath: "assets/"
      assetpath_is_relative_to_siteroot: false
      libraries: 
        - foundation
        - manimejia
      splash: 
      script: | 
      style: | 
      publish:
        main: true
        print: false
        featured: false
        draft: false
      hide:
        topbar: false
        title: false
        footer: false
  -
    scope:
      type: "page"
      path: "projects"
    values:
      layout: "project" 
      category: "project"

config:
  name: "Manuel Mej&iacute;a"
  description: "Experience Architect, Web Developer, and Multimedia Creative"
  domain: manimejia.me
  author:
    name: Manuel Mej&iacute;a
    locality: Ann Arbor
    state: Mi.
    website: http://manimejia.me
    email: hello-at-manimejia.me
    phone: (971) 533 7591
    services:
     - Experience Architect
     - Web Developer
     - Multimedia Creative

  lang: en
  favicons:
    - /resources/favicon-152.png
  topbar:
    toggle: 
    right:
      - name: Services
        url: "/#services"
      - name: Portfolio
        url: "/#portfolio"
      - name: About Me
        url: "/#aboutme"
      - name: Resum&eacute;
        url: "/resume.html"
        #class: small button
        #hasform: false
