---
title: Manimejia.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    libraries:
    - foundation
    - manimejia
- scope:
    path: ''
    type: pages
  values:
    title: 
    category: 
    tags: 
    layout: page
    printable: false
    assetpath: assets/
    assetpath_is_relative_to_siteroot: false
    libraries:
    - foundation
    - jquery_ui
    - uix
    - manimejia
    splash: 
    script: ''
    style: ''
    publish:
      main: true
      print: false
      featured: false
      draft: false
    hide:
      topbar: false
      title: false
      footer: false
- scope:
    path: projects
    type: pages
  values:
    layout: project
    category: project
    hide:
      title: true
- scope:
    path: resume/manimejia.pdf
  values:
    redirect_from: "/resume"
markdown: kramdown
permalink: none
include:
- blog
- resume
exclude:
- CNAME
- Gemfile
- LICENSE
- Rakefile
- README.md
- resources
- foundation/scss
sass:
  sass_dir: theme/foundation/scss
gems:
- jekyll-redirect-from
base_url: http://manimejia.me/
layouts_dir: "./_layouts"
available_libraries:
- name: foundation
  js:
  - "/theme/foundation/js/vendor/jquery.js"
  - "/theme/foundation/js/vendor/modernizr.js"
  - "/theme/foundation/js/foundation.min.js"
  css:
  - "/theme/foundation/icons/foundation-icons.css"
  - "/theme/foundation/css/normalize.css"
- name: jquery_ui
  js:
  - "/theme/jquery-ui/jquery-ui.js"
- name: uix
  js:
  - "/theme/uix-widgets/uix-widgets.js"
- name: skrollr
  js:
  - "/theme/skrollr/skrollr.min.js"
- name: skrollr_stylesheets
  js:
  - "/theme/skrollr/skrollr.stylesheets.min.js"
  head:
  - "<link rel='stylesheet' type='text/css' href='/theme/manimejia/skrollr-stylesheet.css'
    data-skrollr-stylesheet />"
- name: skrollr_menu
  js:
  - "/theme/skrollr/skrollr.menu.min.js"
- name: slick
  js:
  - "/theme/slick/slick.min.js"
  css:
  - "/theme/slick/slick.css"
- name: manimejia
  js:
  - "/theme/manimejia/manimejia.js"
  css:
  - http://fonts.googleapis.com/css?family=Josefin+Sans:300,400|Open+Sans:400italic,600,400
  - "/theme/manimejia/foundation-manimejia-fourcolor.css"
sources:
  unsplash: https://source.unsplash.com
config:
  name: Manuel Mej&iacute;a
  description: Creative Web Architect
  domain: manimejia.me
  author:
    name: Manuel Mej&iacute;a
    locality: Ann Arbor
    state: Mi.
    website: http://manimejia.me
    email: hello(at)manimejia.me
    phone: "(971) 533 7591"
    services:
    - Web Developer
    - Experience Architect
  lang: en
  favicons:
  - "/assets/manimejia-gravatar-icon-256.png"
  topbar:
    toggle: "<span class='hidden-for-small-only hidden-for-medium-up'>Toggle Menu</span>"
    right:
    - name: Experience
      url: "/#experience"
    - name: Capacity
      url: "/#capacity"
    - name: Clients
      url: "/#clients"
    - name: Portfolio
      url: "/portfolio"
    - name: Resum&eacute;
      url: "/resume/manimejia.pdf"
      class: button alert
      target: _blank
    - name: Contact
      url: "#contact"
# comment line
