label: "Sr. Web Developer & Architect"
summary: "As an autodidactic web professional since 2001, I offer both Web Development and Information Architecture services in an iterative balance of careful planning and __'roll up your sleeves'__ good work." 

list: 
- label: Web Developer
  icon: html5
  summary: "As a front end focused Web Developer, I contribute to both the client and server side code using a wide range of frameworks, platforms, libraries, and tools. With intelligent, standards compliant, object oriented, and modular contributions, I work collaboratively in multidisciplinary teams toward the creation of modern web solutions for a wide range of clients."

- label: Architect
  icon: layout
  summary: "As a technically minded Information Architect, my primary expertise is in the R&D of tools that effect clear communication in any medium. From complex navigational structures, to client-server APIs; from user stories to technical specifications; from accessibility requirements, to SEO optimization; these are the delicate interfaces that present the biggest challenges in designing and developing modern interactive web applications."
