summary: |
  As an autodidactic web professional since 2001, I offer user experience focused architecture, design, and development services in an iterative balance of careful planning, clear communication, and ‘roll up your sleeves’ good work.

list: 

- label: Way Finder
  icon: eye
  color: warning
  unsplash: NkEH30uoe8o
  summary: |
    I design clear and efficient user journeys through complex and unfamiliar systems.
  accomplishments: 
    - project_id: EC/CareNet-Elder-Care-Portal
      description: |
        In 2009, I led the early product design for Elite Care’s second generation elder care management system. I produced a comprehensive collection of UX deliverables to define a unified product experience with functionality across multiple platforms. 
    - project_id: OSU/Graduate-School-Website
      description: |
        In 2012, while documenting the OSU Graduate School's legacy website, I found that critical information was being communicated multiple times in different ways. In streamlining this content, I greatly improved the readability of the new website.
    - project_id: OSU/Graduate-School-Website
      description: |
        In 2013, I led the website redesign efforts for the OSU Graduate School. During this time, I designed an efficient and highly praised browsing interface to address the long standing challenge of finding information about current graduate programs.

- label: People Watcher
  icon: results-demographics
  color: alert
  unsplash: 2TlAsvhqiL0
  summary: |
    I use research and observations to better understand a project's target audience.
  accomplishments:
    - project_id: MM/Artist-Webdrop-Drupal-Distribution
      description: |
        In 2008, one of my early entrepreneurial ventures was to develop a “plug and play” website solution for visual artists. To research, I asked a hundred artists how they typically market their works and how they use the web to support their business.
    - project_id: EC/CareNet-Elder-Care-Portal
      description: |
        In 2009, while designing Elite Care’s elder care management system, I visited many campus homes to observe the residents and staff in situ. This provided insightful contextual data that would otherwise have been unavailable to the product team.  
    - project_id: OSU/Graduate-Education-Toolkit
      description: |
        In 2014, I spearheaded the user experience design efforts for this graduate student application system. Through regular interviews with students and faculty, I gained insights about their typical workflow and periodically tested wireframe designs.

- label: Bridge Builder
  icon: share
  color: success
  unsplash: JibIPPrvITE
  summary: |
    I listen to diverse stakeholder perspectives and facilitate clear communication.
  accomplishments:
    - project_id: INFR/UA-Portfolio
      description: |
        In 2015, at InfoReady in Ann Arbor, I participated in the weekly prioritization of customer feedback. My participation in this process was especially sought after, due to my experience and accuracy in understanding user input and product constraints. 
    - project_id: INFR/UA-Portfolio
      description: |
        In 2015, during a tumultuous product development cycle at InfoReady, I maintained clear communication with the designers, developers, and product team. I facilitated a cross-discipline understanding of un-documented requirements and proposed solutions. 
    - project_id: SHUK/InfoShuk-Business-Analytics-App
      description: |
        In 2016, at an early stage startup in Ann Arbor, I led multiple brainstorm sessions to fine tune the direction of development work each week. This iterative process led to an efficient working environment with rapid prototypes being produced at a regular pace.

- label: Code Explorer
  icon: wrench
  color: info
  unsplash: xNdPWGJ6UCQ
  summary: |
    I contribute functional and scalable code at every stage of the product lifecycle.
  accomplishments:
    - project_id: OSU/Graduate-Education-Toolkit
      description: | 
        In 2014, during development of this graduate admissions management system, I  integrated the responsive Bootstrap framework and related libraries into their VisualForce front end built on the SalesForce cloud platform. The resulting hybrid Bootstrap/ Visualforce components that came from this integration were usable for many projects in the future.
    - project_id: INFR/UA-Portfolio
      description: |
        Upon being hired at InfoReady in 2015, I dove head on into javascript development using AngularJS. It was my first of many adventures with this thick-client framework, yet far from a beginners lesson. With deep understanding of the application growing UI requirements, I was able to re-architect the entire front end to deliver a more polished and scalable solution in less time than other estimates. 

- label: Trail Blazer
  icon: flag
  color: warning
  unsplash: o-xzF35Qskc
  summary: |
    I choose bold paths toward possible futures while making the most of situational resources.
  accomplishments:
    - project_id: BFAS/Best-Friends-Virtual-Tour
      description: |
        In 2001, I proposed, designed, and built a unique multimedia virtual tour of the Best Friends Animal Sanctuary campus. While such a product was ahead of it's time and typically out of budget for a growing non-profit, the roadmap I presented was practical and achievable, with clear benefits for all. Utilizing the RIA capabilities of Flash 5, we redefined the landscape of interactive web presentations, putting Best Friends on the map with a dynamic Internet presence and a handful of spinning furry friends.
    - project_id: MM/uix-javascript-controller-library
      description: |
        In 2015, I started an open source javascript library called UIX. This represents a novel approach to building accessible user interface widgets in HTML5. By using WAI-ARIA standard attributes to identify these elements and their intended interactions, I was able to provide “out of the box” semantic and keyboard navigable UI widgets, shaving hours of redundant work for “accessibility compliant” front end developers.


#- label: Problem Solver 
#  icon: check
#  color: success
#  unsplash: 3f4sQIums6k
#  summary: |
#    staying focused on the bigger picture as requirements evolve through each iteration




#    - project_id: EC/CareNet-Elder-Care-Portal
#      description: |
#        In 2009, while researching the requirements of the CareNet system, I reverse engineered their undocumented legacy code base to discover its core processes and functionality. By incorporating these findings into the new application architecture, I saved Elite Care thousands of dollars in what would have otherwise been a “from scratch” code rewrite without the guidance of the legacy development team. 


#    - project_id: OSU/Graduate-School-Website
#      description: |
#        In 2012, during the Graduate School's website redesign process, I met individually with every stakeholder, to collect and integrate diverse requirements into a single project definition. This resulted in the creation of a new design that met everyone’s evolving needs while remaining simply architected and easy to administer.


