label: "Sr. Front End Developer & Architect"
summary: As an experienced web professional since 2001, I offer scalable, usable, and accessible solutions to complex design and interface problems.

list: 
- label: Web Developer
  icon: html5
  summary: In 15+ years, I have worked with a wide range of both client and server side frameworks, platforms, libraries, and tools. With intelligent, standards compliant, object oriented, and modular code contributions, I have guided the  development of web projects for many successful and nationally recognized organizations. 

- label: Interface Architect
  icon: layout
  summary: From rest [APIs](https://en.wikipedia.org/wiki/Application_programming_interface) to human [UIs](https://en.wikipedia.org/wiki/User_interface) to [a11y](https://en.wikipedia.org/wiki/Computer_accessibility) interfaces, my constant and unifying goal in every project is to craft the tools for effective communication. With many years of experience in a wide range of products, I have learned that these delicate interfaces present the biggest challenges in designing modern interactive web applications. 
