summary: |
  As an autodidactic web professional since 2001, I offer user experience focused architecture, design, and development services in an iterative balance of careful planning, clear communication, and ‘roll up your sleeves’ good work.

list: 

- label: Pattern Finder
  icon: graph-bar
  color: info
  unsplash: NkEH30uoe8o
  summary: |
    revealing and exploiting the hidden order in unknown, unmanaged, or unexplored systems
  accomplishments:
    - project_id: OSU/Graduate-School-Website
      description: |
        I unearthed a deeply nested and recurrent pattern of content reiteration in the Graduate School's legacy website, where critical information was communicated multiple times in various ways. It’s resolution led to a content strategy covering the same information in 60% fewer destination pages, thereby saving hundreds of maintenance hours in the website's lifespan. 
    - project_id: EC/CareNet-Elder-Care-Portal
      description: |
        In preparing for this project, I reverse engineered thier recursively dependent wet spaghetti legacy code base to discover its core processes and functionality. By incorporating these findings into the new application architecture, I saved Elite Care thousands of dollars in what would have otherwise been a “from scratch” code rewrite without the guidance of the legacy development team. 

- label: People Watcher
  icon: results-demographics
  color: warning
  unsplash: 2TlAsvhqiL0
  summary: |
    understanding the human experience by observing our reactions to and interactions with the created environment
  accomplishments:
    - project_id: OSU/Graduate-School-Website
      description: |
        For this website redesign, I iterated through multiple user interface designs and observed the interactions of actual users with each version. This provided real world data, which I used to narrow the field of potential UX solutions. 
    - project_id: EC/CareNet-Elder-Care-Portal
      description: |
        I visited many Elite Care campus homes to observe the residents and staff in situ, while designing a new front end UX for their care reporting and monitoring system. This provided insightful contextual information that would otherwise have been unavailable to the remote development team.

- label: Code Explorer
  icon: wrench
  color: alert
  unsplash: xNdPWGJ6UCQ
  summary: |
    recursively navigating the coded world with agility and commitment, making use of what works and commenting out the rest 
  accomplishments:
    - project_id: INFR/UA-Portfolio
      description: |
        On being hired at InfoReady, I dove head on into javascript development using AngularJS. It was my first of many adventures with this thick-client framework, yet far from a beginner’s lesson. With deep understanding of the application’s growing UI requirements, I was able to re-architect the entire front end to deliver a more polished and scalable solution in less time than other estimates. 
    - project_id: OSU/Graduate-Education-Toolkit
      description: | 
        During development of this Graduate School application, I fearlessly integrated the responsive Bootstrap framework and related libraries into their VisualForce front end built on the SalesForce cloud platform. The resulting hybrid Bootstrap/ Visualforce components that came from this integration will be usable for many projects in the future.

- label: Bridge Builder
  icon: share
  color: warning
  unsplash: 4i__Q9jTe74
  summary: |
    listening to and connecting stakeholder perspectives to maximize available resources in any context
  accomplishments:
    - project_id: INFR/UA-Portfolio
      description: |
        During a tumultuous development cycle, I maintained clear communication with the designers, developers, project team, and investors providing a cross-discipline understanding of requirements and continuous progress toward a timely release. 
    - project_id: OSU/Graduate-School-Website
      description: |
        I met individually with every stakeholder during this website redesign process, to collect and integrate diverse requirements into a single project definition. This facilitated creation of a new design that met everyone’s evolving needs while remaining simply architected and easy to administer.

- label: Trail Blazer 
  icon: eye
  color: success
  unsplash: o-xzF35Qskc
  summary: |
    cutting new paths with visionary confidence and practical respect for the legacy paradigms
  accomplishments:
    - project_id: MM/uix-javascript-controller-library
      description: | 
        For this project, I concieved and developed a novel approach to building accessible user interface widgets in HTML5. By using WAI-ARIA standard attributes to identify these elements and their intended interactions, I was able to provide “out of the box” semantic and keyboard navigable UI widgets, shaving hours of redundant work for “accessibility compliant” front end developers.
    - project_id: BFAS/Best-Friends-Virtual-Tour
      description: |
        In 2001, I pitched, designed, and implemented a unique multimedia online tour of the Best Friends physical campus. With the RIA capabilities of the new Flash 5 and a head full of spinning panoramas, we redefined the landscape of interactive web presentations, putting BFAS on the map with a dynamic internet presence.

- label: Problem Solver 
  icon: checkbox
  color: alert
  unsplash: 3f4sQIums6k
  summary: |
    putting it all together, while listening to stakeholders, looking for patterns, designing for users, contributing to code, and sparking new ideas
  accomplishments:
    - project_id: SHUK/InfoShuk-Business-Analytics-App
      description: |
        While working for this early startup, I led multiple brainstorm sessions to fine tune the direction and priorities for development work each week. This iterative design process led to rapid and evolving prototypes being put in front of potential clients at a regular pace. While each version was more complex than the last, we were able to incorporate every change into a growing and scalable architecture for future application development.
    - project_id: OSU/Graduate-School-Website
      description: |
        As a needed solution to an historic problem with the Oregon State University Graduate School website, I designed a novel navigational experience for students and faculty to quickly find pertinent information about the hundreds of [graduate programs](http://gradschool.oregonstate.edu/programs) and available [funding opportunities](http://gradschool.oregonstate.edu/awards). With the realization that this content represents 80% of their daily website traffic, I set out to improve this valuable user experience. What once required about 10 interactions for each user to find the desired information, now requires about 4 interactions.
