label: "Sr. Web Developer & Experience Architect"
summary: "
  As an autodidactic creative professional, 
  my unique superpowers are curiosity and optimism. 
  Without such, I would be little more than a skilled monkey." 

list: 
- label: Web Developer
  icon: html5
  summary: "
    As an experience focused Web Developer, I contribute 
    to both the client and server side code using a variety 
    of languages, frameworks, libraries, and tools. 
    With intelligent, standards compliant, object oriented, 
    and modular contributions, I work collaboratively in 
    multidisciplinary teams toward the creation of modern 
    web solutions for a wide range of clients."

- label: Experience Architect
  icon: layout
  summary: "
    As a technically minded Experience Architect, 
    my primary expertise is in the R&D of tools that effect 
    clear communication in any medium. From comprehensive 
    user stories, to optimized layout and navigational tools; 
    from deeply accessible content, to search engine friendly 
    content; I focus on smoothing the delicate interfaces that 
    define modern interactive web applications."

