label: "Sr. Web Developer & Architect"
summary: As an experienced web professional since 2001, I guide the development of complex, scalable, and highly usable solutions for business, non-profit, and acadamic clients.

list: 
- label: Web Developer
  icon: html5
  summary: "In the last 15+ years, I have guided both the client side and server side developement of many modern web aoplications, using a wide range of both open source and proprietary frameworks, platforms, libraries, and tools. With intelligent, standards compliant, object oriented, and modular code, I have contributed to the development of web projects for many successful and nationally recognized organizations."

- label: Architect
  icon: layout
  summary: "As an [autodidactic](https://en.wikipedia.org/wiki/Autodidacticism) and technically minded Information Architect, my primary expertise is in the R&D of tools that effect clear communication in any medium. From complex navigational structures, to client-server APIs; from user stories to technical specifications; from accessibllity requirements, to SEO optimization; these are the delicate interfaces that present the biggest challenges in designing and developing modern interactive web applications."
